WIP: Burve Integration Tests (#6)
* Change LiqFacet to allow minting with multiple tokens and simply LPToken while handling that

* Add the transitive transfer of tokens from user to lp to burve. And allow for USDT by using forceApprove

* Fix src compilation errors. Unfortunately we'll have to update test compilation

* edge tests

* 5/12

* wip liq shares

* basic simplex tests

* run swap tests

* EvmError: MemoryOOG

* simplify balance call for init state

* migrate view facet

* lower amp

* simple liq tests

* 7/15 swap

* swap facet tests 11/11

* simple add/sub homSet

* cleanup / issue with balance after

* vertex + burve setup

* Adding SimSwap to swap facet

* simplify remappings

* build

* edge facet tests

* liq facet debugging

* deployment under size

* Add sanity check to token inputs

* Add method to LiqFacet for adding multiple tokens at once

* Include fix catching equals when using mulDivX256

* Add getVertexId to simplex facet

* Starting e4626 test

* Some initial tests

* Basic tests for E4626

* More sophisticated e4626 test

* wip

* wip liq facet

* wip tests

* Add untested LP token interface for minting with multiple tokens

* all but multi-burve

* check not needed

* wrap multi tests + clean

* deployment

* wip fork testing

* dolomite tests

* Squashed commit of the following:

commit d783dc7fc41c84bb444c209f2089672549cfd554
Author: Terence An <terence@itos.fi>
Date:   Mon Feb 10 15:50:58 2025 -0500

    Ensure fetched edge is always valid instead of relying on slot0

commit 232a7a8af57097a137693d595efd6e122689faa9
Author: Terence An <terence@itos.fi>
Date:   Mon Feb 10 11:22:55 2025 -0500

    Add numVertices view method in SimplexFacet

commit fddcff8ef4215670722ecc209381d0f27de329c3
Author: Terence An <terence@itos.fi>
Date:   Mon Feb 10 11:08:25 2025 -0500

    Add simSwap and getSqrtPrice view methods to SwapFacet

commit d540ae2bf8c3dd3d259af0fb70aa03820546f1b6
Author: ItosTerence <115845392+ItosTerence@users.noreply.github.com>
Date:   Sun Feb 9 14:21:23 2025 -0500

    [H-03] Normalizing token weights can result in a revert (#15)

commit 47aa3d11b2939faf8d8f50d900a5678225ca7c24
Author: ItosTerence <115845392+ItosTerence@users.noreply.github.com>
Date:   Sun Feb 9 11:33:48 2025 -0500

    [L-07] Validate input tokens for user contract calls (#17)

commit 63aa230f4b8953e0433114ab259417a07662d115
Author: ItosTerence <115845392+ItosTerence@users.noreply.github.com>
Date:   Sun Feb 9 11:25:45 2025 -0500

    Fix [L-05] and [L-02] by using SafeERC20.forceApprove (#16)

commit 52d8b3509689055a0333bf391a0edc4a8d71ce3a
Author: Terence An <terence@itos.fi>
Date:   Fri Jan 31 20:32:18 2025 -0500

    [M-05] Add missing SimplexFacet selectors in Diamond.

    Also adds one view function, getVertexId, to SimplexFacet

commit 7d064923de1603c9d79ed45796ba1cc56555c194
Author: Brian Broeking <117868840+itos-brian@users.noreply.github.com>
Date:   Sat Feb 8 18:04:29 2025 -0800

    [L-01] LPToken.burn() spend allowances even when account == msg.sender (#10)

commit 2fb58522b452be2804256c92058de9e062e1e8e8
Author: Terence An <terence@itos.fi>
Date:   Sat Feb 8 21:03:53 2025 -0500

    Related to [L-03]. No bug to fix here but switching methodology

commit 92b201da6d303b68161452376555ad67883a7d3d
Author: Terence An <terence@itos.fi>
Date:   Sat Feb 8 20:56:23 2025 -0500

    [L-04] Calculating total assets upon depositing does not subtract the temp withdrawal amount

commit b158f591cf6bceeda65286959e16b91363470640
Author: Terence An <terence@itos.fi>
Date:   Sat Feb 8 20:19:03 2025 -0500

    [L-09] Incorrect Boundary Check for lowTick and highTick

commit f2fc4bc3f14ae231bbc1deb6497bceb0384dd832
Author: Brian Broeking <117868840+itos-brian@users.noreply.github.com>
Date:   Sat Feb 8 16:41:38 2025 -0800

    [M-06] Missing supportsInterface Selector from DiamondLoupeFacet (#13)

commit a2a6cc139536df46bfbc3de1056777c18fb27d58
Author: urlaubaitos <118572453+urlaubaitos@users.noreply.github.com>
Date:   Sat Feb 8 19:05:35 2025 -0500

    [C-04] Draining approved tokens by unrestricted uniswapV3MintCallback() (#9)

commit f383c7f93cadc853d27a0722c5af908211c44f98
Author: brian <117868840+itos-brian@users.noreply.github.com>
Date:   Sat Feb 8 16:00:06 2025 -0600

    [C-01] Incorrect parenthesis usage results in a completely wrong calculation

commit e0930639405dd1fe023cc6b2b73fbd8882b17146
Author: brian <117868840+itos-brian@users.noreply.github.com>
Date:   Sat Feb 8 15:57:16 2025 -0600

    [C-02] Incorrect calculation of cumulativeValue in LiqFacet::addLiq results in less shares for users

* compile

* build

* update integration tests

* consolidate

* ignore broadcast files

* event testing

* viewRemoveLiq

* not doing anymore

* additional fork testing

* fork tests and bartio

---------

Co-authored-by: Terence An <terence@itos.fi>